# Generated by Django 3.1 on 2020-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videorequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoTitle',
            field=models.CharField(max_length=30),
        ),
    ]
